#ifndef _JETSON_STATUS_H
#define _JETSON_STATUS_H

typedef int Status;

typedef enum 
{
    SUCCESS,
    INSUFFICIENT_RESOURCES,
    INVALID_DATA,
    FILE_HANDLING_ERROR,
    FILE_OPEN_ERROR,
    FILE_CLOSE_ERROR,
    I2C_WRITE_ERROR,
    I2C_READ_ERROR,
    IOCTL_ERROR,
    BUFFER_EMPTY,
    MUTEX_ERROR,
    CONDVAR_ERROR,
    GENERIC_ERROR
} STATUS_VALUES;

#endif
